### ISSUE TITLE
dns_sd fails assertion on Centos 5

### ISSUE THREAD

**Issue by lordmundi** [dongola7/tcl_bonjour#2]
I would really love to use this package, but I'm having trouble isolating a weird error coming out of the avahi dns_sd compatibility library as soon as I go to use the resolve command.

First off, running on Ubuntu 10.04 64 bit with a tcl8.5 tclsh, things seem to work fine.  Running on Centos 5, however, I get a weird dns_sd assertion error.  It looks like:

> tclsh8.5: compat.c:442: sdref_free: Assertion `__ret == 0' failed.

It appears that the dns_sd library is dying when it tries to destroy the mutex associated with the sdref.

So, I began troubleshooting.  I have found the following differences between the machine that works and the one that doesn't, beyond the obvious OS and 32/64 bit difference:
1. The machine that works (which is a newer OS) oddly has the libdns_sd version of 1.0.0 while the Centos 5 box has 1.0.1.  Could it be that there is a bug in 1.0.1 that is causing the issue that isn't in 1.0.0?
2. The machine that works had tcl8.5 compiled with thread support and the Centos box doesn't.  However, I downloaded tcl 8.5.8 onto the box that works and compiled it specifically without thread support and ran a test like this:

<pre>
<code>
setenv LD_LIBRARY_PATH /home/frankie/installs/tcl8.5.8/unix
../../tcl8.5.8/unix/tclsh
% info exists ::tcl_platform(threaded)
0
% exit
../../tcl8.5.8/unix/tclsh client_edge.tcl
</code>
</pre>

and it worked fine.  This makes me think the issue is not due to the missing thread support in the tcl library.

Any ideas?  I've looked through the tcl_bonjour code and don't see anything obviously wrong.

FG

**Comment by dongola7** [comment]
I was able to confirm that Ubuntu 10.10 also works without problems.  Looking online, it would appear that Ubuntu 10.10 uses avahi version 0.6.27, while CentOS 5 uses version 0.6.16 (despite the fact that it has a dns_sd of 1.0.1).

I tried building avahi 0.6.16 on Ubuntu 10.10, but ran into a large number of missing dependencies which I have been unable to resolve.  Would you be able to upgrade to avahi 0.6.27 on the CentOS box, or downgrade on the Ubuntu box in order to confirm the problem behavior?

I can start downloading the CentOS ISOs tonight to try it out, but it will take a while to pull them all down.

**Comment by lordmundi** [comment]
was doing some research, and I have a strong feeling that this is the issue:

http://avahi.org/ticket/96

Notice that this was fixed in 0.6.17, so it would make sense that the 16 version would have the bug.  I don't think 17 is in the yum repositories so I'll have to try and upgrade it from source I suppose.  I'll report back once I have a chance to try it.

**Comment by lordmundi** [comment]
ok, I can confirm that running with 0.6.17 does fix the issue.  I had to build it from source on Centos 5 unfortunately, but this confirms that it is not an issue with this package.
